# Generated by Django 4.2.3 on 2023-07-11 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('subject', models.CharField(max_length=100)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('image_profile', models.ImageField(upload_to='teacher_profiles/')),
                ('video', models.FileField(upload_to='teacher_videos/')),
            ],
        ),
    ]
